apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-user
  namespace: prometheus-operator
spec:
  encryptedData:
    admin-password: AgCTPlEQd1L0jcoM620lQf36hM1ix7XqT07jn27F6SWj8vEtZePUbR6Z/MC/88UQZJnCzv+pUeXb4Ad26c5xbgaHpgxJ5300JRfgud3cGC17DV4YXW5aoYlomDiYUR1xnX0/ABqyZ3gN51BHYqd786eWVBGnQMzoMRBnmgPACo0GNzB/psmWopVbJAhdPaV2wV1NM37J4LKVw38CpTEH5a18POBv0D+aQLydxHt0RwfdIk517sC/h+vY8H3t5TeYPGIcHwovUSFjkP8lGm9nndawdRoetNituES9dhEW9Cy5eg82qqk3+wCUazLzTVbXo59C7RQvs6DWkgwJcRGvWUPEebfoRN20IpLxjVzuXxJToEad8ioI+5LMs89sQw7smyvQpxlP69yVSAS6xujlbnfBK3VJuADGqZm7/NPp33LANuPwBUalDfJ+170tBtVrclvFGdvohAmujqwtaKb6Jgf/IXM71g1zKQYPNoOmbkhIb+W9NpRjKWz1XY1rJlkhN+NuzsjuW+ZzmHHg5t/+nNN4LxgWhiPu3U1nToKON1Zdc6XXn1oGJZvxpuF9LpWNsxaV/FPJNfGatUoSsOxue0hUojCRpicjevYULVTXQl2nqKJ5rTwo5M2whje0/BqR8V7J7MSs5w4FRwwq9qSaVrvEEZF/Hd8oRMaUfSUciwXuXqcpt2nu+KTqAIA3WAn6B+zyb1qWyQ59kw==
    admin-user: AgBnm9Aky+hOVAhDh1n3xXi39J8cqR0ioWGIzFAToWyrHUtnqLrDIiISHOKAxNDWcyFtOcrfNiSlwdDBo8Bw/dEffaDC4jwb9wbY7zBA4IDgXf7iOXyRrKFaz1QFwC4USm09qqrTDfoTnBk0dWwO35ESnzTZXysWcFDlQIqt5WNSAt3NV3LnBGYYCdjCm9gUMCD5oWidiIbzmhewzvUCwAQvVpgKflKsdHG20eFAbtBflU+OACO24ewTzSP+HYLPf0QURrijE28medXYvu/FsCnXqv+e4WQ6BXSYc+1JRtKKaflPUGeqU7Tx7hdbq568MN4D/WU9VJLQ+RnLPRktSe/+Vkhh/v3+6fDZxSylicQQgGw4YyTmxjcsDbgd/jYRwSHW3UM+bimoNNDcPw1yPz5+AIBv6H15R10Lfxh74h2QFEd/D4D1eYoHlJ5bnsIgYSzVggvyDPCdflKsVtT+kg56Yv24d+lDi62fqgkDt0EPoMgWwAiqaAZry2Z+ay0/Bs1gFIfhfTFpTUabI/vviKeJ9YPh9KPnGfb/vQmyJAPuyZOMuRY82A0JV6Z2wKZES7tHp3p7QjmL6CkmYCQ2fVOzUDaFpRW4XlYUcquesNyA4XkX19nEqcOPGFzrPEPSUVxFIZLPEPlK9i4InyttBcjXhlO9QgLHrBshrVo7u8+1o+FZIBcwdQ8roU5xnDPFkgty4ntFhA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-user
      namespace: prometheus-operator
    type: Opaque
