apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-user
  namespace: prometheus-operator
spec:
  encryptedData:
    admin-password: AgAp0hGGKqvrzB5eMsNJynazUlMYfPBAzHOTIqeAzgXtP80C9a6m2xxR4OyM2V9t/fe6uC2PWLOt1/a4TgJhd9ZWTu+kyiFOvFDD9kCuiix8wWEdJW2ETzohj+KViNFGVhzWpISBx9e9dvqwoBWo2awrboSI04BQaENxSiFUuXDVyijAY+DDcGjN8J7uLR3BGF8eenNhSAAko0+iP47/t+mhUZbLmcXb6xpjWxNjBZ1F1nBbctGZOM3ZzigtS7cMV81RRcKjrGWX7AnlvaWZb68JIYvMShhYdmqF/uWXvmHuaOsQGmP0S+FtCJNDgTGgpfPSTD5Di5CyajQlZeaatPHclU2/2JtyFzOKWd2L7RuiHmDpJu1+zecm0vEN5wXSyO2AS4MqAvdMGcAIR8gqGuBrogOxSoNrA9Kjr319HyBLYkXyQxCJHkzlzwhedynRlyaKacorQn+Nw88I1/LK6dSyf9t1SBfDBdyqDi37Xkf+M61pmJjFoMF/5rQFWETc1Tnby8xvb54aoEYG4yrGhtfAy3Yk3E57JajVxAjQyGciwtMvB7c8agoje+GfDGftD6v5CRMWWCx4lATRVikonqRSqUatyCGQ4XXFCBrsnbvGyrbMx7eOGt3I3v/NGiQ831ISSTLrVtGr9AvlqHQdCS8r0T1ycTPJhHRUj21Ke+VZ+8HjW+AWtxv63xbMnsbdrQZ5SrYSwZ5wJA==
    admin-user: AgBGLmJBGQpGX4nJ9npSijKdt3Guv3cPd6bYAZluTQ8E8GqxQ2jD9pGEgpPU8dkziA1GrMHil+4+IWO82XW5BbzS+2gJYeYRovMyRZrzJ0CKMGhCbcCAMJj0227y1MOCb5ZrBObqyu+6AqMNay10788zY5Qpnabr4Fp500Nbx2ZTRlHVGnmR1yP9/rZezkjjjR3nOCT1phdmd6rpO9nu47XMJVNbqNP4VZ8NMVJWPOBOlWdEvt8JV6jI79+dOw07hk65H8574xZXhJT5M2EfrmB7s/sj39n/QWDjufLcTZj8gkAgajGGke4hrJhQiShFtNzziCR7rHjGDhu/6t85dmaBqszVP3EpMiUU1OC2dmzTxL9EgL81SiacOHFt5yi8GNZGu5RvRCEtW8psOH68ba/V7FCAvPsYX7VECNQ0SinJatqgU6jr/2EIaSeEEervTjGI1dXewA6HAMtZxSrbbs+bc+mcNnWwKkVFTaawOl1EXSYC+a9kGsTQwmsZh4lNp2YbFC0PsiMIzOkz+RZ6jQQ9NiU0pb4YYOCtzBRCRCzXTR6J9GTmroi9VsYA1m7FUmpV0dD1N7B/ZtmsM2sgr9YOlaK1LhpIa6Z4vDtC4Yx6PY+pg9RJu4LF1BJJKjs/6zi6H0D2WR13nTEAX1GDFrIXoDUe4YYizHj9u9RCwtAUZZ98l54YnZTT9OCPNGHLoCjofRITJw==
  template:
    metadata:
      creationTimestamp: null
      name: admin-user
      namespace: prometheus-operator
status: {}

