apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo
  namespace: argocd
spec:
  destination:
    namespace: echo
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: echo-server
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
          - host: 'echo.t.efgh.nl'
            paths: ['/']
          tls:
          - hosts: ['echo.t.efgh.nl']
            secretName: echo-tls
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
    repoURL: https://ealenn.github.io/charts
    targetRevision: 0.3.0
  syncPolicy: {}
